### PR TITLE
Adding JEC files for 2018 data and MC.

### PR DESCRIPTION
**Pull request by sroychow**

### CODE REVIEW

**Comment by bianchini** [comment]
Hi @sroychow: can you also modify postproc to take the correct JEC in input?

**Comment by sroychow** [comment]
@bianchini The postproc is already updated for 2018 and included in this commit.

**Comment by bianchini** [comment]
uhm... sure? For data, it is empty at the moment: https://github.com/emanca/nanoAOD-tools/blob/wmass/python/postprocessing/wmass/postproc.py#L91 and for MC we still have V3:
https://github.com/emanca/nanoAOD-tools/blob/wmass/python/postprocessing/wmass/postproc.py#L76

**Comment by bianchini** [comment]
I can't see any change to postproc in this PR

**Comment by sroychow** [comment]
Please have a look:-
https://github.com/emanca/nanoAOD-tools/blob/b3803d4373dd6ff66148bdc2a20a0a2df871a889/python/postprocessing/wmass/postproc.py

**Comment by bianchini** [comment]
yes, sorry, my fault! I. missed it!
Thanks a lot, I am merging it

**Pull request merged**
